services:
  frontend:
    container_name: frontendDev2
    build: ./frontend/
    depends_on:
      - backend
    # ports:
    #   - "40:40"
    networks:
      - net

  backend:
    container_name: backendDev2
    build: ./backend/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./logfile.log:/app/logfile.log
    networks:
      - net

  postgres:
    container_name: postgresDev2
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/postgres
    networks:
      - net

  nginx:
    container_name: nginxDev2
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
