services:
  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - backend
    # ports:
    #   - "40:40"
    networks:
      - net

  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./logfile.log:/app/logfile.log
    networks:
      - net

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
