services:
  frontend:
    container_name: frontend
    build: ./frontend/
    depends_on:
      - backend
    ports:
      - "40:40"
    networks:
      - net

  backend:
    container_name: backend
    build: ./backend/
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - net

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data/postgres
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
