export const navLinks = [
  {
    id: "home",
    title: "Главная",
  },
  {
    id: "console",
    title: "Панель управления",
  },
  {
    id: "price",
    title: "Цены",
  },
];

export const pricing = [
  {
    id: "standart",
    title: "Standart",
    price: "2.39",
    text: "Стандартный облачный сервер",
    color: "border-gray-500",
    har1: "1 ядра CPU",
    har2: "50 Gb SSD",
    har3: "8 Gb RAM",
    har4: "Публичный IP",
    har5: "Интернет до 100 Мбит/сек",
  },
  {
    id: "extended",
    title: "Extended",
    price: "10.70",
    text: "Стандартный облачный сервер с расширенными возможностями",
    color: "border-yellow-300",
    har1: "1 ядра CPU",
    har2: "50 Gb SSD",
    har3: "8 Gb RAM",
    har4: "Публичный IP",
    har5: "Интернет до 100 Мбит/сек",
  },
  {
    id: "super",
    title: "Super",
    price: "40",
    text: "Облачный сервер с расширенными возможностями",
    color: "border-red-300",
    har1: "1 ядра CPU",
    har2: "50 Gb SSD",
    har3: "8 Gb RAM",
    har4: "Публичный IP",
    har5: "Интернет до 100 Мбит/сек",
  },
  {
    id: "prime",
    title: "Prime",
    price: "120",
    color: "border-red-500",
    bg_color: "bg-red-300",
    text: "Премиальный облачный сервер с расширенными возможностями",
    har1: "1 ядра CPU",
    har2: "50 Gb SSD",
    har3: "8 Gb RAM",
    har4: "Публичный IP",
    har5: "Интернет до 100 Мбит/сек",
  },
];
