"""serverHardware

Revision ID: 77cace1d1420
Revises: 6f4a2e131576
Create Date: 2025-05-12 22:54:40.735265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cace1d1420'
down_revision: Union[str, None] = '6f4a2e131576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ServerHardvareRegion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('ServerHardwareOrm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PROC', 'MEMORY', 'DISK', name='serverhardvaretype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ServerHardwareOrm')
    op.drop_table('ServerHardvareRegion')
    # ### end Alembic commands ###
