"""add created_at to Users

Revision ID: b26a7ca719c8
Revises: 3f28d2ffd686
Create Date: 2025-02-06 10:17:49.085027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26a7ca719c8'
down_revision: Union[str, None] = '3f28d2ffd686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
